version: '3.8'
services:
  app:
    image: 3n1hye/newcracker-server
    platform: linux/amd64
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/newcracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: containerName
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE : newcracker

    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: